### ISSUE TITLE
Fails to integrate  with Dovecot 2.3.0

### ISSUE THREAD

**Issue by hmolina** [st3fan/dovecot-xaps-plugin#21] opened 2018-01-08 19:40 UTC
Hi,

After update dovecot to version 2.3.0, the plugin fails to compile:
The message is:

cc    -std=gnu99 -fPIC -shared -Wall -I/usr/include/dovecot -DHAVE_CONFIG_H xaps-plugin.c -o xaps_plugin.so
xaps-plugin.c: In function 'xaps_transaction_begin':
xaps-plugin.c:153:12: error: too few arguments to function 'zbox->super.transaction_begin'
     return zbox->super.transaction_begin(box, flags);
            ^~~~
xaps-plugin.c: In function 'xaps_mailbox_allocated':
xaps-plugin.c:207:30: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     box->v.transaction_begin = xaps_transaction_begin;
                              ^
xaps-plugin.c: In function 'xaps_transaction_begin':
xaps-plugin.c:154:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
gmake: *** [Makefile:43: xaps_plugin.so] Error 1

Any idea? Thanks in advance!

**Comment by freswa** [comment] 2018-01-08 20:59
Current tag ist not compatible with 2.3.0 as also stated in the README. This is wip and a release with compatibility to the latest dovecot will be published in the next days.
Also duplicate of #18.

**Closed by freswa** 2018-01-08 20:59 UTC
